// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.Ragu {
    public class VersionInfo {
        public static string appVersion = "2.1.3";
        public static string longVersion = "2.1.3-20221103-cd313fea";
        public static string buildDate = "20221103";
    }
}
