// This file is auto-generated by BuildVersion
// Before editting, check out the application's build environment for use of BuildVersion
using System;
namespace org.herbal3d.Ragu {
    public class VersionInfo {
        public static string appVersion = "2.2.10";
        public static string longVersion = "2.2.10-20230316-c015e86f";
        public static string buildDate = "20230316";
    }
}
